In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'raw/train_wide.csv'

df = pd.read_csv(path)

df.head()

,fecha_dato,user_id,sex,age,is_new_customer,seniority_months,region_code,region_name,income,segment,...,target_biz-4_90,target_dep-6_30,target_dep-6_60,target_dep-6_90,target_loan-4_30,target_loan-4_60,target_loan-4_90,target_card-3_30,target_card-3_60,target_card-3_90
0,2016-05-28,15893,M,63,0.0,256,28.0,MADRID,430477.41,INDIVIDUALS,...,0,0,0,0,0,0,0,0,0,0
1,2016-05-28,15906,F,56,0.0,237,28.0,MADRID,81005.49,VIP,...,0,0,0,0,0,0,0,0,0,0
2,2016-05-28,15930,F,52,0.0,256,28.0,MADRID,246128.34,VIP,...,0,0,0,0,0,0,0,0,0,0
3,2016-05-28,15932,M,71,0.0,256,28.0,MADRID,232144.20,INDIVIDUALS,...,0,0,0,0,0,0,0,0,0,0
4,2016-05-28,15939,F,57,0.0,209,28.0,MADRID,232954.74,INDIVIDUALS,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.drop(columns=['fecha_dato'], inplace=True)

df.head()

,user_id,sex,age,is_new_customer,seniority_months,region_code,region_name,income,segment,dep-7,...,target_biz-4_90,target_dep-6_30,target_dep-6_60,target_dep-6_90,target_loan-4_30,target_loan-4_60,target_loan-4_90,target_card-3_30,target_card-3_60,target_card-3_90
0,15893,M,63,0.0,256,28.0,MADRID,430477.41,INDIVIDUALS,0,...,0,0,0,0,0,0,0,0,0,0
1,15906,F,56,0.0,237,28.0,MADRID,81005.49,VIP,0,...,0,0,0,0,0,0,0,0,0,0
2,15930,F,52,0.0,256,28.0,MADRID,246128.34,VIP,0,...,0,0,0,0,0,0,0,0,0,0
3,15932,M,71,0.0,256,28.0,MADRID,232144.20,INDIVIDUALS,0,...,0,0,0,0,0,0,0,0,0,0
4,15939,F,57,0.0,209,28.0,MADRID,232954.74,INDIVIDUALS,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df['sex'].isna().sum()

np.int64(3)

In [5]:
df.dropna(subset=['sex'], inplace=True)

In [6]:
df['sex'].isna().sum()

np.int64(0)

In [7]:
df['age'].isna().sum()

np.int64(0)

In [8]:
df.loc[df["age"] < 0, "age"] = np.nan

In [9]:
df['age'].isna().sum()

np.int64(0)

In [10]:
df.loc[(df["age"] < 14) | (df["age"] > 95), "age"] = np.nan

In [11]:
df['age'].isna().sum()

np.int64(3635)

In [12]:
df.dropna(subset=['age'], inplace=True)

In [13]:
df['age'].isna().sum()

np.int64(0)

In [14]:
df['is_new_customer'].isna().sum()

np.int64(0)

In [15]:
df['is_new_customer'].value_counts()

is_new_customer
0.0    354667
1.0     17836
Name: count, dtype: int64

In [16]:
df['seniority_months'].isna().sum()

np.int64(0)

In [17]:
df.loc[df['seniority_months'] < 0, 'seniority_months'] = np.nan

In [18]:
df['seniority_months'].isna().sum()

np.int64(2)

In [19]:
df.dropna(subset=['seniority_months'], inplace=True)

In [20]:
df['seniority_months'].isna().sum()

np.int64(0)

In [21]:
df['region_code'].isna().sum()

np.int64(0)

In [22]:
df['region_name'].isna().sum()

np.int64(0)

In [23]:
df['segment'].isna().sum()

np.int64(1438)

In [24]:
df['segment'] = df['segment'].fillna('UNKNOWN')

In [25]:
df['segment'].isna().sum()

np.int64(0)

In [26]:
output_path = 'processed/v1/train_wide_cleaned.csv'

df.to_csv(output_path, index=False)